fix #124
AOMediaCodec/iamf pull request #161
Opened 2022-11-03 09:03 UTC by sunghee-hwang

2022-11-07 17:58 UTC, felicialim requested changes

2022-11-07 17:58 UTC, felicialim commented on index.bs
> +The order of [=audio_substream_id=]s in this loop shall indicate the order of Audio Frame OBUs in every temporal unit of the IA sequence.
How about introducing syntax to explicitly describe the channel mapping instead of relying on the OBU ordering in the bitstream?

2022-11-08 00:13 UTC, sunghee-hwang commented on index.bs
> +The order of [=audio_substream_id=]s in this loop shall indicate the order of Audio Frame OBUs in every temporal unit of the IA sequence.
I am not sure what exactly you want to introduce. 
Do you want to remove the restriction which the order of audio frame OBUs for an audio element in the bitstream should be kept in every temporal unit?

2022-11-09 02:41 UTC, sunghee-hwang commented on index.bs
> +The order of [=audio_substream_id=]s in this loop shall indicate the order of Audio Frame OBUs in every temporal unit of the IA sequence.
How about this change?
For scene-based audio element, the order of audio_element_ids in this loop shall indicate the order of substreams in the one channelgroup for the scene-based audio element. 
For channel-based audio element, the order of audio_element_ids in this loop shall indicate the order of substreams in one or more channelgroups for the channel-based audio element. 
Where, the order of the audio frame OBUs for a given audio element  in every temporal units of the IA sequence does not necessarily same as the order of substreams in one or more channelgroups for the audio element. But, the order of the audio frame OBUs for the audio element shall be same in every temporal units of the IA sequence.

NOTE: i.e the order of audio_element_ids in this loop is same as Channel Mapping field in Ogg Opus.

2022-11-29 00:30 UTC, tdaede commented
Missing mapping of stereo/mono substreams to channel mappings.

2022-11-29 00:42 UTC, tdaede commented
Section 10.2.5 contains the ordering rules for the channels.

It would be good to reference this from section 4.2.1.

2022-11-29 02:02 UTC, sunghee-hwang commented
> Missing mapping of stereo/mono substreams to channel mappings.

Section 10 IAC Generation Process define the order of substreams in each ChannelGroup.

The order of substreams in each ChannelGroup shall be as follows:

In ChannelGroup for Ambisonics: The order shall conform to [[RFC8486]](https://github.com/AOMediaCodec/iamf/pull/161#biblio-rfc8486).

In ChannelGroup for Scalable Channel Audio: The order shall conform to following rules:

Coupled Substreams comes first and followed by non-coupled Substreams.

Coupled Substreams for surround channels comes first and followed by one(s) for top channels.

Coupled Substreams for front channels comes first and followed by one(s) for side, rear and back channels.

Coupled Substreams for side channels comes first and followed by one(s) for rear channels.

Center channel comes first and followed by LFE and followed by the other one.

Where, non-coupled substream is a coded substream from one of non-coupled channels.

2022-12-05 05:52 UTC, felicialim commented on index.bs
> +In other words, when [=audio_element_type=] = 0, the order of [=audio_substream_id=]s in this loop shall indicate the order of the substreams in the [=num_layers=] = r number of ChannelGroups for the
Just want to check my understanding: 

1. This is just mapping the order of audio_substream_id's in the loop in audio_element_obu() to the order in which they are referred to in the scalable/ambisonics configs. And it places no restrictions on how the Audio Frame OBUs are ordered in the IA sequence, except that they should be consistent in temporal units, when temporal units exist (i.e. with temporal delimiter OBU) in the IA sequence?

2. The order in which audio_substream_id is defined in the loop in audio_element_obu() matches the order of the substreams referred to in the scalable config as follows:

[ [r=0, n=0], [r=0, n=1], ..., [r=0, n=N], [r=1, n=0], ..., [r=1, n=N], ..., [r=R, n=N] ]

where r = channel group index, R is number of channel groups, n = channel index per channel group and N is number of channels in a given channel group?   

If so, this scheme looks fine to me. I would suggest specifying the order (see 2.) more explicitly.

2022-12-06 02:26 UTC, sunghee-hwang commented on index.bs
> + - Where, i = 0, 1, 2, ..., [=num_substreams=].
It was a typo. `audio_element_id` should be fixed to `audio_substream_id`.

2022-12-06 02:26 UTC, sunghee-hwang commented on index.bs
> +In other words, when [=audio_element_type=] = 0, the order of [=audio_substream_id=]s in this loop shall indicate the order of the substreams in the [=num_layers=] = r number of ChannelGroups for the
updated to implement this.

2022-12-06 23:25 UTC, felicialim reviewed
The mapping scheme sounds fine to me. My remaining comments are editorial. 

Could I suggest simplifying the text (using the below) to describe the mapping scheme you're proposing?


audio_substream_id shall specify the unique ID associated with the audio substream that is used to reconstruct this audio element.

Let a particular ChannelGroup's substream be indexed as [c, n_c], where 

- c = [1, ..., C] is the ChannelGroup index,
- C is the number of ChannelGroups,
- n_c = [1, ..., N_c] is the substream index in the c-th ChannelGroup,
- N_c is the number of substreams in the c-th ChannelGroup.

The i-th audio_substream_id maps to a ChannelGroup's substream as follows, where i is the index of the array:

[
  [1, 1], [1, 2], ..., [1, N_1], 
  [2, 1], [2, 2], ..., [2, N_2], 
  ..., 
  [C, 1], [C, 2], ..., [C, N_c]
].

A ChannelGroup is defined in [[#iacgeneration]]. The order of the substreams in each ChannelGroup., i.e. the semantics of n_c, is specified in [[#syntax-scalable-channel-layout-config]].

2022-12-06 23:25 UTC, felicialim commented on index.bs
> + - Where, the order of the substreams does not need to be same as the order of Audio Frame OBUs for the given audio element in the IA sequence. But, the order of the Audio Frame OBUs shall be same in
I this should go somewhere else in the spec that talks about how to ordering the AudioFrame OBUs in the temporal units, since it's related to ordering OBUs in an IA sequence.

2022-12-07 00:08 UTC, sunghee-hwang commented on index.bs
> + - Where, the order of the substreams does not need to be same as the order of Audio Frame OBUs for the given audio element in the IA sequence. But, the order of the Audio Frame OBUs shall be same in
It makes a sense.

2022-12-07 00:09 UTC, sunghee-hwang commented
> The mapping scheme sounds fine to me. My remaining comments are editorial.
> 
> Could I suggest simplifying the text (using the below) to describe the mapping scheme you're proposing?
> 
> audio_substream_id shall specify the unique ID associated with the audio substream that is used to reconstruct this audio element.
> 
> Let a particular ChannelGroup's substream be indexed as [c, n_c], where
> 
> * c = [1, ..., C] is the ChannelGroup index,
> * C is the number of ChannelGroups,
> * n_c = [1, ..., N_c] is the substream index in the c-th ChannelGroup,
> * N_c is the number of substreams in the c-th ChannelGroup.
> 
> The i-th audio_substream_id maps to a ChannelGroup's substream as follows, where i is the index of the array:
> 
> [ [1, 1], [1, 2], ..., [1, N_1], [2, 1], [2, 2], ..., [2, N_2], ..., [C, 1], [C, 2], ..., [C, N_c] ].
> 
> A ChannelGroup is defined in [[#iacgeneration]]. The order of the substreams in each ChannelGroup., i.e. the semantics of n_c, is specified in [[#syntax-scalable-channel-layout-config]].

Sounds good.

2022-12-07 01:09 UTC, felicialim approved these changes

2022-12-13 00:06 UTC, tdaede commented
Please rebase so that it is mergeable.

2022-12-13 00:13 UTC, tdaede commented
Feel free to merge when rebased.

2022-12-13 00:58 UTC, merged