Fix #189
AOMediaCodec/iamf pull request #191
Opened 2022-11-23 01:07 UTC by sunghee-hwang

2022-11-28 23:37 UTC, felicialim requested changes

2022-11-28 23:37 UTC, felicialim commented on index.bs
> +- The allowed numbers of [=output_channel_count=] are (1+n)^2, where n = 1, 2, 3, 4, 5.
How about allowing n = 0, 1, ..., 14 following RFC8486?

2022-11-29 00:46 UTC, tdaede commented on index.bs
> +- The allowed numbers of [=output_channel_count=] are (1+n)^2, where n = 1, 2, 3, 4, 5.
Will update to be n = 0-14.

2022-11-29 17:31 UTC, felicialim approved these changes

2022-12-06 01:13 UTC, merged