Fix #188, #176 and #175
AOMediaCodec/iamf pull request #195
Opened 2022-11-24 10:18 UTC by sunghee-hwang

To fix texts related to parameter definitions and types

***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/iamf/pull/195.html" title="Last updated on Dec 13, 2022, 1:31 AM UTC (2730a76)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/iamf/195/9eaebf1...2730a76.html" title="Last updated on Dec 13, 2022, 1:31 AM UTC (2730a76)">Diff</a>

2022-11-28 23:55 UTC, felicialim requested changes
Thanks for this PR to fix the broken merge. However, it looks like a few things are still missing, I can look into this further.

2022-11-28 23:55 UTC, felicialim commented on index.bs
> +        ReconGainParamDefinition();
This should be recon_gain_info_parameter_data()

2022-11-28 23:55 UTC, felicialim commented on index.bs
> +        DemixingParamDefinition();
This should be `demixing_info_parameter_data()`, where 

```
class demixing_info_parameter_data() {
  unsigned int (3) dmixp_mode;
  unsigned int (5) reserved;
}
```

2022-11-28 23:55 UTC, felicialim commented on index.bs
> +    leb128() param_definition_type;
I think we want to remove this loop and instead, define the parameters closer to where they are actually used, e.g. here we would want to add it in the scalable channel config.

2022-11-28 23:55 UTC, felicialim commented on index.bs
> +Audio Element OBU and/or Mix Presentation OBU shall map a parameter_id to the parameter defintion type. So, IA decoders can know the definition type mapped to the parameter_id.
The mapping should be available from ParamDefinition(), which should be inherited by all parameter definition classes. So we shouldn't need an additional mapping here.

2022-11-29 05:03 UTC, sunghee-hwang commented on index.bs
> +    leb128() param_definition_type;
If we move them in the scalable channel config, then when we consider a future extension we may need to define new audio element obu if the future version need a parameter for ambisonics.
For future extendibility, I prefer to keep the current location if there is no big difference.

2022-11-29 05:28 UTC, sunghee-hwang commented on index.bs
> +Audio Element OBU and/or Mix Presentation OBU shall map a parameter_id to the parameter defintion type. So, IA decoders can know the definition type mapped to the parameter_id.
My mistake.
I intended just to explain the mapping information is described in Audio Element OBU and/or Mix Presentation OBU.
I did not intend to define a new mapping.

So, the sentence need to be changed like this:

Audio Element OBU and/or Mix Presentation OBU is mapping a parameter_id to the parameter defintion type. So, IA decoders can know the definition type mapped to the parameter_id.

2022-11-29 22:55 UTC, felicialim requested changes

2022-11-29 22:55 UTC, felicialim commented on index.bs
> +Audio Element OBU and/or Mix Presentation OBU is mapping a parameter_id to the parameter defintion type. So, IA decoders can know the definition type mapped to the parameter_id.
Since parameter block parsers have to handle all the different parameter definition types, consider collecting all the mappings between param_definition_type and Parameter definition in a table here instead of distributing them throughout the spec. This would mean there we can look this up in one convenient location in the spec.

2022-11-29 22:55 UTC, felicialim commented on index.bs
> +  leb128() mix_gain_type;
The motivation behind allowing the inclusion of the default values in the ParamDefinition() was to provide a clean and consistent way throughout the spec for collecting all the parameter definition related data in one place. It also makes it explicit via syntax that default values can be provided. As such, we would prefer putting the default values back in MixGainParamDefinition().

2022-11-29 22:55 UTC, felicialim commented on index.bs
> +        DemixingParamDefinition();
Could you expand on the motivation behind using the DemixingParamDefinition() syntax instead of 
`DemixingParamDefinition demix_param_definition`?

The original motivation for the latter is for reusability and readability. For example, we could have a type of Parameter (e.g. GainParamDefinition) and multiple instances of it for different types of gains. Using the latter syntax, we could then define something like:

```
foo() {
  GainParamDefinition left_channel_gain;
  GainParamDefinition right_channel_gain;
}
```

Of course this generalization wouldn't be required for DemixingParamDefinition(), but we would prefer a single consistent way to express this throughout the spec.

2022-11-29 23:26 UTC, sunghee-hwang commented on index.bs
> +    leb128() param_definition_type;
Optional parameters can be still added without requiring the change of the configuration of an audio element.
Please think it again.

2022-11-29 23:37 UTC, sunghee-hwang commented on index.bs
> +Audio Element OBU and/or Mix Presentation OBU is mapping a parameter_id to the parameter defintion type. So, IA decoders can know the definition type mapped to the parameter_id.
Then mix presentation obu is a good candidate to include all of parameter ids to parse

2022-11-29 23:41 UTC, sunghee-hwang commented on index.bs
> +  leb128() mix_gain_type;
Either is ok for me as long as decoders know if the parameter will present in IA sequence from descriptor obus.

2022-11-29 23:44 UTC, sunghee-hwang commented on index.bs
> +        DemixingParamDefinition();
I think it is a good idea.

2022-11-30 06:10 UTC, sunghee-hwang commented on index.bs
> +  leb128() mix_gain_type;
Copied from the original text.
```
class element_mix_config() {
  MixGainParamDefinition mix_gain;
}

class MixGainParamDefinition extends ParamDefinition() {
  signed int (16) default_mix_gain;
}

default_mix_gain shall specify the default mix gain value to apply when there are no mix gain parameter blocks provided.
```
element_mix_config provides parameter_id which is mapped to mix_gain_parameter_data while MixGainParamDefintion provides default_mix_gain.
Then what does "when there are no mix gain parameter blocks provided." mean?
Does this mean that decoders can not know its presence until getting the parameter_id from IA sequence?
When does decoders need to apply default_mix_gain?
The above sentence creates many following questions. 
Please clarify it.

2022-11-30 06:15 UTC, sunghee-hwang commented on index.bs
> +Parameter definition classes shall inherit from the abstract <dfn noexport>ParamDefinition()</dfn> class.
Copied from the original text.

class element_mix_config() {
  MixGainParamDefinition mix_gain;
}

class MixGainParamDefinition extends ParamDefinition() {
  signed int (16) default_mix_gain;
}

default_mix_gain shall specify the default mix gain value to apply when there are no mix gain parameter blocks provided.
element_mix_config provides parameter_id which is mapped to mix_gain_parameter_data while MixGainParamDefintion provides default_mix_gain.
Then what does "when there are no mix gain parameter blocks provided." mean?
Does this mean that decoders can not know its presence until getting the parameter_id from IA sequence?
When does decoders need to apply default_mix_gain?
The above sentence creates many following questions.
it should be clarified.

2022-11-30 06:18 UTC, sunghee-hwang commented on index.bs
> +        DemixingParamDefinition();
I used demixing_info to align with mix_gain. I also changed demixing_info() class to demixing_info_parameter_data() to align with mix_gain_parameter_data(). Applied the same to recon_gain too.

2022-12-06 01:14 UTC, tdaede commented
Felicia is reviewing the updates.

2022-12-07 00:13 UTC, felicialim commented on index.bs
> +        DemixingParamDefinition demix_info;
demix_info -> demixing_info

Or the other way around, to match its definition in the Semantics section

2022-12-07 00:13 UTC, felicialim commented on index.bs
> +Audio Element OBU and/or Mix Presentation OBU is mapping a parameter_id to the parameter definition type. So, IA decoders can know the definition type mapped to the parameter_id.
Re: specifying param definitions in the top-level mix presentation OBU, I have a similar comment as specifying them in the top-level audio element OBU. Since there are a few loops in the mix presentation OBU, I'm unsure how easy it is to extend it in the future without changing syntax if we introduced a new param that sits in one of those loops.

2022-12-07 00:13 UTC, felicialim commented on index.bs
> +Audio Element OBU and/or Mix Presentation OBU is mapping a parameter_id to the parameter defintion type. So, IA decoders can know the definition type mapped to the parameter_id.
But there are some parameters that apply to audio element, and some to mix presentation?

2022-12-07 00:32 UTC, sunghee-hwang commented on index.bs
> +    leb128() param_definition_type;
I think that is another story. We should not mix two different issues.

2022-12-07 01:07 UTC, felicialim commented on index.bs
> +    leb128() param_definition_type;
Apologies I think I may have misunderstood the original motivation then. My understanding was that it's for future-proofness, was that limited to just ambisonics (and assuming there is no other major changes to ambisonics syntax) and not scalable channel?

2022-12-07 01:17 UTC, sunghee-hwang commented on index.bs
> +    leb128() param_definition_type;
I meant that "to define audio element level parameter" differs from "to define layer level parameter". Two are different issues.
"layer level parameter defining scheme" does not cover "audio element level parameter defining scheme" and vise versa.

2022-12-07 01:23 UTC, sunghee-hwang commented on index.bs
> +    leb128() param_definition_type;
Currently, as we have no layer level parameters, if someone want to define layer level parameter, then it would be a new one which requires new syntaxes. But, as we already have "audio element level parameter defining scheme", adding a new audio element level parameter can be supported by using the current syntaxes.

2022-12-07 07:52 UTC, sunghee-hwang commented on index.bs
> +Audio Element OBU and/or Mix Presentation OBU is mapping a parameter_id to the parameter defintion type. So, IA decoders can know the definition type mapped to the parameter_id.
Yes, right. we need two information as follows:
1. The mapping information between parameter id(s) and an audio element.
2. The mapping information between parameter id(s) and a mixed audio.
 
I think that descriptor obus should provide them without help of data obus so that IA parsers or decoders can make sure all of mapping information before accessing data obus.
For example, when we choose one mix presentation obu, IA parsers or decoders should know all of mapping information without accessing data obus.

2022-12-07 08:02 UTC, sunghee-hwang commented on index.bs
> +Audio Element OBU and/or Mix Presentation OBU is mapping a parameter_id to the parameter definition type. So, IA decoders can know the definition type mapped to the parameter_id.
I think that the current structure would work per audio element id and/or mix presentation id.
```
leb128() num_parameters;
for (i = 0; i < num_parameters; i++) {
    leb128() parameter_id;
    leb128() parameter_name;
}
```
It requires more bits if we have multiple mix presentations while the mix presentation can choose parameters what he want to take.

2022-12-08 01:16 UTC, felicialim commented on index.bs
> +    leb128() param_definition_type;
I see, this is fine with me. Thanks for clarifying.

2022-12-08 01:22 UTC, felicialim commented on index.bs
> +Audio Element OBU and/or Mix Presentation OBU is mapping a parameter_id to the parameter defintion type. So, IA decoders can know the definition type mapped to the parameter_id.
Sorry, I was referring to table in the Semantics section that maps param_definition_type and Parameter definition. It is currently sits in "4.1.7. Audio Element OBU Syntax and Semantics", which seems strange given there are mix parameters there too. But I don't think Mix Presentation OBU semantics is the right place for it either, I think a good place is in the Semantics section of parameter_block_obu(). And perhaps the `param_definition_type` in both audio element OBU and mix presentations OBU can then reference that table. 

As for your comment, I fully agree with it.

2022-12-08 01:49 UTC, sunghee-hwang commented on index.bs
> +Parameter definition classes shall inherit from the abstract <dfn noexport>ParamDefinition()</dfn> class.
Thanks for the clarification.

As we have the duration field in Parameter Block OBU, it can be covered by below Case 2. It requires more bits but IA parsers or decoders can make sure the situation clearly before accessing data OBUs.
Case1: Default_mix_gain only to cover all of timeline
Case2: Parameter block only to cover all of timeline.

2022-12-12 21:54 UTC, felicialim commented on index.bs
> +Parameter definition classes shall inherit from the abstract <dfn noexport>ParamDefinition()</dfn> class.
I think we're missing Case3, where we have parameter blocks covering some of the timeline, and when it doesn't, the default values apply. We should be able to cover Case3 without having to define a new flag for it with the original proposal.

2022-12-12 21:56 UTC, felicialim commented on index.bs
> +Parameter definition classes shall inherit from the abstract <dfn noexport>ParamDefinition()</dfn> class.
Since we are defining in element_mix_config(), the IA parsers should be able to know whether there is a default value, before accessing Data OBUs.

2022-12-12 21:59 UTC, felicialim commented on index.bs
> +Audio Element OBU and/or Mix Presentation OBU is mapping a parameter_id to the parameter defintion type. So, IA decoders can know the definition type mapped to the parameter_id.
My remaining comment was an editorial one about where the param_definition_type table sits, but I'm happy to create a separate PR to address that to avoid blocking this.

2022-12-12 22:12 UTC, sunghee-hwang commented on index.bs
> +Parameter definition classes shall inherit from the abstract <dfn noexport>ParamDefinition()</dfn> class.
Do you intend to have all of 3 cases?

2022-12-12 22:17 UTC, felicialim commented on index.bs
> +Parameter definition classes shall inherit from the abstract <dfn noexport>ParamDefinition()</dfn> class.
Yes, it would be great if we can offer the flexibility of being able to have a default param value for most of the time, and then every once in a while, a custom value might be applied.

2022-12-12 22:46 UTC, sunghee-hwang commented on index.bs
> +Parameter definition classes shall inherit from the abstract <dfn noexport>ParamDefinition()</dfn> class.
If we would have case3, then I don't think that we need case 1&2.

2022-12-12 23:10 UTC, sunghee-hwang commented on index.bs
> +Parameter definition classes shall inherit from the abstract <dfn noexport>ParamDefinition()</dfn> class.
I made go back to original case3 only.

2022-12-12 23:31 UTC, felicialim approved these changes

2022-12-13 00:08 UTC, tdaede commented
Please rebase to make mergeable.

2022-12-13 00:13 UTC, tdaede commented
Feel free to merge once rebased.

2022-12-13 01:37 UTC, merged