Fix #148
AOMediaCodec/iamf pull request #205
Opened 2022-11-30 07:36 UTC by sunghee-hwang

2022-11-30 17:55 UTC, felicialim approved these changes

2022-12-05 22:26 UTC, felicialim requested changes

2022-12-05 22:26 UTC, felicialim commented on index.bs
> +- One set of Descriptor OBUs shall be placed at the beginning of IA sequence and followed by a sequence of data OBUs.
In the description below, an IA sequence is allowed to be composed of a series of OBUs in the repeating pattern of descriptor OBUs followed by data OBUs, repeated as many times as needed, and not just once. Could we update this sentence to reflect that?

2022-12-07 00:16 UTC, felicialim commented on index.bs
> +- One set of Descriptor OBUs shall be placed at the beginning of IA sequence and followed by a sequence of data OBUs.
It just seems that as an introduction sentence, it is incomplete as-is so I'd suggest updating it, to avoid potential confusion when reading the sub-sections below.

2022-12-07 00:23 UTC, sunghee-hwang commented on index.bs
> +- One set of Descriptor OBUs shall be placed at the beginning of IA sequence and followed by a sequence of data OBUs.
You may update it directly.^^

2022-12-07 06:11 UTC, felicialim commented on index.bs
> +- One set of Descriptor OBUs shall be placed at the beginning of IA sequence and followed by a sequence of data OBUs.
I created a PR #214, feel free to merge the relevant parts here if preferred.

2022-12-13 00:10 UTC, tdaede commented
These changes should be covered by #214. Closing.

2022-12-13 00:10 UTC, closed without merging