Fix #297, Rigidly specified order for Descriptors
AOMediaCodec/iamf pull request #316
Opened 2023-03-09 07:14 UTC by sunghee-hwang

2023-03-13 10:34 UTC, yeroro requested changes

2023-03-13 10:34 UTC, yeroro commented on index.bs
>  2. All Codec Config OBUs
So in the case of base profile, which only allows one unique Codec Config OBU but many other descriptor OBUs (refreshing is allowed), should the Codec Config OBU be repeated redundantly? Or can it be missing from the refreshing set?

2023-03-14 00:20 UTC, tdaede commented
Please address yeroro's comment, but the change looks good otherwise.

2023-03-14 00:43 UTC, sunghee-hwang commented on index.bs
>  2. All Codec Config OBUs
The Codec Config OBU should be repeated redundantly

2023-03-14 22:46 UTC, yeroro approved these changes

2023-03-20 19:51 UTC, merged