Fix #315, to update 10.2.8 and its subsections
AOMediaCodec/iamf pull request #318
Opened 2023-03-09 07:49 UTC by sunghee-hwang

2023-03-13 10:44 UTC, yeroro requested changes

2023-03-13 10:44 UTC, yeroro commented on index.bs
> +This section provide a guideline to generate loudness_info().
"provides"

2023-03-13 10:44 UTC, yeroro commented on index.bs
> +For a given Mix Presentation OBU and a given [=loudness_layout=] of a sub-mix of the given Mix Presentation OBU, followings are processed in order to produce loudness_info().
"the" followings

2023-03-13 10:44 UTC, yeroro commented on index.bs
> +- Each of Audio Elements specified in the sub-mix of the give Mix Presentation OBU is rendered to the given [=loudness_layout=] according to [=rendering_config()=] for the Audio Element.
"Each Audio Element" or "Each of the Audio Elements"

2023-03-13 10:44 UTC, yeroro commented on index.bs
> +- All of Audio Elements specified in the sub-mix of the give Mix Presentation OBU are summed, and then applies [=mix_gain=] according to [=output_mix_config()=] for the sub-mix.
"All Audio Elements" or "All of the Audio Elements"

2023-03-13 10:44 UTC, yeroro commented on index.bs
> +- Each of Audio Elements specified in the sub-mix of the give Mix Presentation OBU applies [=mix_gain=] according to [=element_mix_config()=] for the Audio Element.
s/give/given

2023-03-14 00:20 UTC, tdaede commented
Mergeable with yeroro's editorial comments addressed.

2023-03-14 22:53 UTC, yeroro approved these changes
Approve after the editorial changes.

2023-03-14 22:53 UTC, yeroro commented on index.bs
> +- Each of Audio Elements specified in the sub-mix of the given Mix Presentation OBU is rendered to the given [=loudness_layout=] according to [=rendering_config()=] for the Audio Element.
"Each Audio Element" or "Each of the Audio Elements"

2023-03-14 22:53 UTC, yeroro commented on index.bs
> +- All of Audio Elements specified in the sub-mix of the given Mix Presentation OBU are summed, and then applies [=mix_gain=] according to [=output_mix_config()=] for the sub-mix.
"All Audio Elements" or "All of the Audio Elements"

2023-03-20 19:53 UTC, tdaede commented
This one still has a couple editorial comments.

2023-03-20 23:04 UTC, merged