Fix #275, Fix #305, Fix #306, update ID linking scheme
AOMediaCodec/iamf pull request #320
Opened 2023-03-10 07:42 UTC by sunghee-hwang

2023-03-10 23:20 UTC, jwcullen approved these changes

2023-03-13 11:00 UTC, yeroro requested changes

2023-03-14 00:25 UTC, tdaede commented
Mergeable once yeroro's comments are addressed.

2023-03-14 04:19 UTC, sunghee-hwang commented on index.bs
> +The below figure shows the linking scheme among IDs in obu_header or ids in obu payload.
The header of Audio frame obu can have one of audio substream ids between ID0 to ID21.

2023-03-14 22:57 UTC, yeroro commented on index.bs
> +	- There are two Substreams (audio_substream_id = 0 and 1) which are composing of this audio element. The audio_substream_id = 0 and the audio_substream_id = 1 are linked to the Audio Frame OBUs with
Please address.

2023-03-14 23:11 UTC, sunghee-hwang commented on index.bs
> +	- There are two Substreams (audio_substream_id = 0 and 1) which are composing of this audio element. The audio_substream_id = 0 and the audio_substream_id = 1 are linked to the Audio Frame OBUs with
> Please address.

Please clarify what it needs to be addressed.

2023-03-15 05:26 UTC, yeroro commented on index.bs
> +	- There are two Substreams (audio_substream_id = 0 and 1) which are composing of this audio element. The audio_substream_id = 0 and the audio_substream_id = 1 are linked to the Audio Frame OBUs with
As mentioned in the previous comment https://github.com/AOMediaCodec/iamf/pull/320#discussion_r1133759961

Please replace "which are composing of" with "in".

2023-03-15 05:40 UTC, yeroro approved these changes

2023-03-20 19:56 UTC, merged