Fix #326, semantic of obu_size
AOMediaCodec/iamf pull request #327
Opened 2023-03-15 07:21 UTC by sunghee-hwang

2023-03-15 14:18 UTC, jwcullen requested changes
Approved after fixed typo. I think encoding the size this way is better.

2023-03-15 14:18 UTC, jwcullen commented on index.bs
> +<dfn noexport>obu_size</dfn> indicates the size in bytes of the OBU immediately following the obu _size field of the OBU.
Minor typo "obu _size" has an extra space. "obu_size".

2023-03-15 16:11 UTC, jwcullen approved these changes

2023-03-16 06:18 UTC, yeroro requested changes

2023-03-16 06:18 UTC, yeroro commented on index.bs
> -For this obu, the obu header (2 bytes) shall be set to 0xF807 (in case of [=obu_redundant_copy=] = 0) or FC07 (in case of [=obu_redundant_copy=] = 1) for this version of the specification.
We can keep these sentences, just update to correct values:
```
0xF807 --> 0xF806
FC07   --> 0xFC06
```

2023-03-16 07:46 UTC, sunghee-hwang commented on index.bs
> -For this obu, the obu header (2 bytes) shall be set to 0xF807 (in case of [=obu_redundant_copy=] = 0) or FC07 (in case of [=obu_redundant_copy=] = 1) for this version of the specification.
The values can be kept. But I am afraid that they may generate misunderstanding.

The values are correct for this version of the specification. But if we consider a future version with obu_extension_flag = 1, the values would be no longer correct.
That is the reason why I deleted the sentence.
Please consider it again.

2023-03-16 23:34 UTC, yeroro commented on index.bs
> -For this obu, the obu header (2 bytes) shall be set to 0xF807 (in case of [=obu_redundant_copy=] = 0) or FC07 (in case of [=obu_redundant_copy=] = 1) for this version of the specification.
I see. Yeah I agree the Spec doesn't have to be unnecessarily restrictive.

2023-03-16 23:35 UTC, yeroro approved these changes

2023-03-20 23:07 UTC, merged