Fix #365, clarified sample format for every sample to be sync sample
AOMediaCodec/iamf pull request #366
Opened 2023-04-18 07:25 UTC by sunghee-hwang

2023-04-24 15:23 UTC, yeroro commented
Can someone with more knowledge of MP4 review this? I am afraid I cannot.

2023-04-24 18:53 UTC, tdaede requested changes

2023-04-24 18:53 UTC, tdaede commented on index.bs
> +- One IA Sample data shall be one or more consecutive temporal units (after removing Temporal Delimiter OBUs if present) for every IA Sample to be sync sample.
I think this should still be as before, one temporal unit == one IA sample.

2023-04-24 18:53 UTC, tdaede commented on index.bs
> +- If [=num_samples_to_trim_at_start=] < [=num_samples_per_frame=], every IA Sample except the last IA Sample shall have the same number (N > 0) of temporal units.
Basically even if we trim more than entire audio frame (or even an entire temporal unit) we should still have it be a distinct IA sample. It will still be trimmed by the edit list information as normal.

2023-04-24 23:08 UTC, tdaede commented on index.bs
> +- If [=num_samples_to_trim_at_start=] < [=num_samples_per_frame=], every IA Sample except the last IA Sample shall have the same number (N > 0) of temporal units.
So this allows multiple temporal units per IA sample in all cases.

2023-04-24 23:12 UTC, tdaede commented on index.bs
> +	- The [=num_samples_per_frame=] value in the Codec Config OBU, which indicates the duration of one audio frame, is reflected in the 'stts' or 'trun' box based on [=IA Sample=] except the last [=IA S
If we allow more than one temporal unit / audio frame per IA sample, then num_samples_per_frame should match the duration of the IA sample.

2023-04-24 23:32 UTC, tdaede commented
This design means that temporal blocks no map 1:1 to IA Samples. This means that the encoder has more freedom to map, but also means that when temporal units are stripped during packaging, they will not be re-created when demuxing. I need to review this deeper to see if it will work correctly.

Alternately, either we could leave it as is with a 1:1 mapping, and do a simpler PR that simply limits parameter blocks such that a 1:1 mapping works with every sample being sync samples, or allow multiple audio frames inside a single temporal unit. @shawnisingh will take a look at this in more detail as well.

2023-04-24 23:38 UTC, tdaede commented
I'll also review this for any technical blockers, assuming that we go with this method, now that I better understand what is being achieved.

2023-04-25 01:34 UTC, sunghee-hwang commented on index.bs
> +- One IA Sample data shall be one or more consecutive temporal units (after removing Temporal Delimiter OBUs if present) for every IA Sample to be sync sample.
> This design means that temporal blocks no map 1:1 to IA Samples. This means that the encoder has more freedom to map, but also means that when temporal units are stripped during packaging, they will not be re-created when demuxing. I need to review this deeper to see if it will work correctly.
> 
> Alternately, either we could leave it as is with a 1:1 mapping, and do a simpler PR that simply limits parameter blocks such that a 1:1 mapping works with every sample being sync samples, or allow multiple audio frames inside a single temporal unit. @shawnisingh will take a look at this in more detail as well.

If no one has concern, then I would prefer one temporal unit = one audio frame = one IA sample with every sample being sync samples for v1. (For this, we need to limit parameter blocks such that the duration of parameter block = the duration of audio frame).
Instead of that, one IA sample = multiple temporal unit (one temporal unit = one audio frame) or IA sample = one temporal unit with multiple audio frames is moved to v2.

2023-05-01 20:38 UTC, tdaede commented on index.bs
> +	- The duratin of [=IA Sample=], which is reflected in 'stts' or 'trun' box, is calculated based on the number of audio frames which [=IA Sample=] includes and the [=num_samples_per_frame=] value in
small typo: duration

2023-05-01 20:49 UTC, tdaede commented
I reviewed how the spec would operate with this current PR with several temporal units per sample and my main concern is that when we unpack this back to a bitstream, any temporal OBUs added are now only added per sample, e.g. it does not round trip. I tried to find places where making the temporal units less frequent would break things and found the following text:

> Every Temporal Unit shall have Temporal Delimiter OBU or no Temporal Unit shall have Temporal Delimiter OBU.

I suppose the demuxer could parse the bitstream and add back multiple temporal delimiter OBUs based on reading audio frame OBUs (or just not output them... it does make temporal delimiter OBUs seem a bit vestigal if it is easy to determine where they should go just by parsing the other OBUs)

2023-05-01 20:50 UTC, tdaede approved these changes
This gets an approval from me because I believe it technically doesn't break anything because you are always allowed to demux to a stream without temporal delimiters, but I think that issue should be addressed in more detail (or we go with 1:1 mapping)

2023-05-01 23:11 UTC, merged