Issue #384: Clarify Opus output sample rate should be 48 kHz
AOMediaCodec/iamf pull request #385
Opened 2023-05-02 01:37 UTC by jwcullen

2023-05-08 21:33 UTC, tdaede requested changes

2023-05-08 21:33 UTC, tdaede commented on index.bs
> +The offset shall be indicated in the number of ticks at the sample rate specified in the corresponding substream, Codec Config OBU, or [[#codec-specific]] section.
Perhaps just say codec specific section, and then for each of our codecs, add a definition. For PCM, tick rate would be sample rate. Maybe even make up a variable name for this value.

2023-05-08 21:33 UTC, tdaede requested changes

2023-05-08 21:33 UTC, tdaede commented on index.bs
> +An IA decoder must use a playback sample rate of 48 kHz as defined in [[!RFC7845]].
"An IA decoder assumes a sample rate of 48kHz for all timing information."

Alternately, if we define a term such as tick rate:

"Opus substreams use a tick rate of 48kHz".

2023-05-22 19:01 UTC, tdaede commented
If you want I can push changes on this PR.

2023-05-22 19:05 UTC, jwcullen commented
@tdaede Yes that is fine. I have been focused on the test vectors, so I didn't get back to this yet.

2023-06-02 13:49 UTC, jwcullen commented
Superseded by #439 and should be rejected once it is merged in.

2023-06-12 18:46 UTC, closed without merging