Fix #382, to clarify the meaning of unique obu_id
AOMediaCodec/iamf pull request #396
Opened 2023-05-11 07:25 UTC by sunghee-hwang

2023-05-11 08:02 UTC, yeroro approved these changes

2023-05-11 20:35 UTC, cconcolato requested changes
I find the new wording still quite confusing. I'm suggesting a different wording for the sentences that define these identifiers. The sentences that use these identifiers also need to be changed.

For example, for `codec_config_id` in https://aomediacodec.github.io/iamf/#obu-audioelement, I would replace:
> codec_config_id indicates the obu_id for the codec config which this audio element refers to.

with:
> codec_config_id indicates the identifier for the codec config which this audio element refers to, as defined in a Codec Config OBU.

Same for `audio_element_id`:
> audio_element_id indicates the identifier of a specific audio element, as defined in an Audio Element OBU, that is used in this mix presentation.  

Same for `parameter_id` in https://aomediacodec.github.io/iamf/#obu-parameterblock:
Replace 
> parameter_id indicates an unique obu_id with [obu_type](https://aomediacodec.github.io/iamf/#obu_type) = OBU_IA_Parameter_Block that is associated with a specific parameter definition. All parameter blocks that provide data for that parameter definition shall have the same parameter_id.

with
> parameter_id indicates the identifier of a Parameter definition, as defined in an Audio Element OBU.

Same for `audio_substream_id` (https://aomediacodec.github.io/iamf/#obu-audioframe)
Replace:
> audio_substream_id indicates an unique obu_id with [obu_type](https://aomediacodec.github.io/iamf/#obu_type) = OBU_IA_Audio_Frame in IA sequences for a given substream. All Audio Frame OBUs of the same substream shall have the same audio_substream_id.
>
> This value must be greater or equal to 22, in order to avoid collision with the reserved IDs for the OBU types OBU_IA_Audio_Frame_ID0 to OBU_IA_Audio_Frame_ID21.

with:
> audio_substream_id indicates the identifier of a substream, as defined in an Audio Element OBU.

2023-05-11 20:35 UTC, cconcolato commented on index.bs
> +<dfn noexport>codec_config_id</dfn> indicates an obu uniquely identifiable by this obu_id and [=obu_type=] = OBU_IA_Codec_Config in IA sequences for a given codec config.
I find the new wording still confusing. The `codec_config_id` does not "indicate an obu". 
```suggestion
<dfn noexport>codec_config_id</dfn> defines an identifier for a codec configuration. Within a IA Sequence, there SHALL be only exactly one Codec Config OBU with a given value of `codec_config_id`. Audio Elements that need a decoder configured based on this codec configuration refer to this identifer.
```

2023-05-11 20:35 UTC, cconcolato commented on index.bs
> +<dfn noexport>codec_config_id</dfn> indicates an obu uniquely identifiable by this obu_id and [=obu_type=] = OBU_IA_Codec_Config in IA sequences for a given codec config.
```suggestion
<dfn noexport>codec_config_id</dfn> defines an identifier for a codec configuration. Within a IA Sequence, there SHALL be only exactly one non-redundant Codec Config OBU with a given value of `codec_config_id`. Audio Elements that need a decoder configured based on this codec configuration refer to this identifer.
```

2023-05-11 20:35 UTC, cconcolato commented on index.bs
> +<dfn noexport>mix_presentation_id</dfn> indicates an obu uniquely identifiable by this obu_id and [=obu_type=] = OBU_IA_Mix_Presentation in IA sequences for a given mix presentation.
```suggestion
<dfn noexport>mix_presentation_id</dfn> defines an identifier for a Mix Presentation. Within an IA Sequence, there shall be exactly one non-redundant Mix Presentation OBU with a given identifier. This identifier may be used by the application to select which Mix Presentation(s) to offer.
```

2023-05-11 20:35 UTC, cconcolato commented on index.bs
> +<dfn noexport>audio_element_id</dfn> indicates an obu uniquely identifiable by this obu_id and [=obu_type=] = OBU_IA_Audio_Element in IA sequences for a given audio element.
```suggestion
<dfn noexport>audio_element_id</dfn> defines an identifier for an Audio Element. Within an IA Sequence, there shall be exactly one non-redundant Audio Element OBU with a given identifier. Mix Presentations that use an Audio Element refer to this identifier. This value shall be greater or equal to 22.
```

2023-05-11 20:35 UTC, cconcolato commented on index.bs
> +<dfn noexport>parameter_id</dfn> indicates an obu uniquely identifiable by this obu_id and [=obu_type=] = OBU_IA_Parameter_Block that is associated with a specific parameter definition. All parameter
```suggestion
<dfn noexport>parameter_id</dfn> defines an identifier for a Parameter. Within an IA Sequence, there shall be only one non-redundant Audio Element OBU with this identifier. Parameter Block OBU refer to the Parameter through this identifier.
```

2023-05-11 20:35 UTC, cconcolato commented on index.bs
> +<dfn noexport>parameter_id</dfn> indicates an obu uniquely identifiable by this obu_id and [=obu_type=] = OBU_IA_Parameter_Block that is associated with a specific parameter definition. All parameter
```suggestion
<dfn noexport>parameter_id</dfn> defines an identifier for a Parameter. Within an IA Sequence, there shall be only one non-redundant Audio Element OBU with this identifier. Parameter Block OBU refer to the Parameter through this identifier.
```

2023-05-11 20:35 UTC, cconcolato commented on index.bs
> +<dfn noexport>audio_substream_id</dfn> indicates an obu uniquely identifiable by this obu_id and [=obu_type=] = OBU_IA_Audio_Frame in IA sequences for a given substream. All Audio Frame OBUs of the s
```suggestion
<dfn noexport>audio_substream_id</dfn> defines an identifier for a substream. Within an IA Sequence, there shall be only one non-redundant Audio Element OBU with this identifier. Audio Frame OBUs that provide coded data for this substream use this identifier.
```

2023-05-12 05:01 UTC, sunghee-hwang commented on index.bs
> +<dfn noexport>audio_element_id</dfn> indicates an obu uniquely identifiable by this obu_id and [=obu_type=] = OBU_IA_Audio_Element in IA sequences for a given audio element.
The last sentence is for audio_substream_id. Right?

2023-05-12 06:39 UTC, sunghee-hwang commented on index.bs
> +<dfn noexport>codec_config_id</dfn> indicates an obu uniquely identifiable by this obu_id and [=obu_type=] = OBU_IA_Codec_Config in IA sequences for a given codec config.
Implemented in [645eb06](https://github.com/AOMediaCodec/iamf/pull/396/commits/645eb063e1d6c370e98995e47f386e06e8664e9e)

2023-05-12 06:39 UTC, sunghee-hwang commented on index.bs
> +<dfn noexport>codec_config_id</dfn> indicates an obu uniquely identifiable by this obu_id and [=obu_type=] = OBU_IA_Codec_Config in IA sequences for a given codec config.
Implemented in [645eb06](https://github.com/AOMediaCodec/iamf/pull/396/commits/645eb063e1d6c370e98995e47f386e06e8664e9e)

2023-05-12 06:39 UTC, sunghee-hwang commented on index.bs
> +<dfn noexport>mix_presentation_id</dfn> indicates an obu uniquely identifiable by this obu_id and [=obu_type=] = OBU_IA_Mix_Presentation in IA sequences for a given mix presentation.
Implemented in [645eb06](https://github.com/AOMediaCodec/iamf/pull/396/commits/645eb063e1d6c370e98995e47f386e06e8664e9e)

2023-05-12 06:40 UTC, sunghee-hwang commented on index.bs
> +<dfn noexport>parameter_id</dfn> indicates an obu uniquely identifiable by this obu_id and [=obu_type=] = OBU_IA_Parameter_Block that is associated with a specific parameter definition. All parameter
Implemented in [645eb06](https://github.com/AOMediaCodec/iamf/pull/396/commits/645eb063e1d6c370e98995e47f386e06e8664e9e)

2023-05-12 06:40 UTC, sunghee-hwang commented on index.bs
> +<dfn noexport>audio_substream_id</dfn> indicates an obu uniquely identifiable by this obu_id and [=obu_type=] = OBU_IA_Audio_Frame in IA sequences for a given substream. All Audio Frame OBUs of the s
Implemented in [645eb06](https://github.com/AOMediaCodec/iamf/pull/396/commits/645eb063e1d6c370e98995e47f386e06e8664e9e)

2023-05-12 06:41 UTC, sunghee-hwang commented on index.bs
> +<dfn noexport>audio_element_id</dfn> indicates an obu uniquely identifiable by this obu_id and [=obu_type=] = OBU_IA_Audio_Element in IA sequences for a given audio element.
Implemented except the last sentence in [645eb06](https://github.com/AOMediaCodec/iamf/pull/396/commits/645eb063e1d6c370e98995e47f386e06e8664e9e)

2023-05-12 16:40 UTC, cconcolato commented on index.bs
> +<dfn noexport>codec_config_id</dfn> indicates an obu uniquely identifiable by this obu_id and [=obu_type=] = OBU_IA_Codec_Config in IA sequences for a given codec config.
Thanks. For your information, I had used GitHub's "suggestion" tool so that you did not have to implement it separately. You just had to hit one of the buttons ("Commit suggestion" or "Add suggestion to batch").

2023-05-12 16:41 UTC, cconcolato commented on index.bs
> +<dfn noexport>audio_element_id</dfn> indicates an obu uniquely identifiable by this obu_id and [=obu_type=] = OBU_IA_Audio_Element in IA sequences for a given audio element.
Sorry, I copied the last sentence in the wrong place. It was meant to be in the definition of `audio_substream_id`.

2023-05-12 16:43 UTC, cconcolato commented on index.bs
> +<dfn noexport>parameter_id</dfn> indicates an obu uniquely identifiable by this obu_id and [=obu_type=] = OBU_IA_Parameter_Block that is associated with a specific parameter definition. All parameter
I see it has been implemented too.

2023-05-12 16:44 UTC, cconcolato approved these changes
Except for the sentence about the value space of audio_substream_id which should be added to the semantics of the audio_substream_id field, I'm fine.

2023-05-22 23:07 UTC, merged