Fix #398, Magic Code OBU Improvement
AOMediaCodec/iamf pull request #424
Opened 2023-05-22 04:27 UTC by sunghee-hwang

Comments for version and profile_version need to be addressed in another issue.

2023-05-22 23:16 UTC, tdaede commented on index.bs
> +NOTE: Non-redundant Magic Code OBU (i.e. [=obu_redundant_copy=] = 0) coming after the first Magic Code OBU is regarded as the start of a new IA sequence. This could happen when concatenating 2 IA Seq
If we define streams that have multiple IA sequences in series, this implies the decoder has to support it (and we would need reference streams in libiamf).

I would suggest removing this NOTE: section for now and only define what happens for a single IA sequence. @cconcolato does that sound reasonable?

2023-05-23 01:27 UTC, cconcolato requested changes

2023-05-23 01:27 UTC, cconcolato commented on index.bs
> +This OBU is used to indicate the start of IA Sequence. So, the first OBU of IA Sequence shall be OBU_IA_Magic_Code.
We could add a NOTE as follows:
```
NOTE: When an IA Sequence is stored in a file, the Magic Code OBU can be used to detect that the file contains an IA Sequence.
```

2023-05-23 01:27 UTC, cconcolato commented on index.bs
> +NOTE: For example, when [=obu_extention_flag=] = 0, the value of this OBU header is 0xF806 or 0xFC06. So, the sync pattern is 0xF806 + ‘iamf’ or 0xFC06 + ‘iamf’.
```suggestion
<dfn noexport>ia_code</dfn> indicates a ‘four-character code’ (4CC), ‘iamf’. 
NOTE: When IA OBUs are delivered over a protocol that does not provide explicit IA Sequence boundaries, a parser may locate the IA Sequence start by searching for the code 'iamf' preceded by specific OBU header values, e.g. assuming [=obu_extension_flag=] is set to 0 and because [=obu_trimming_status_flag=] is set to 0 for a Magic Code OBU, the OBU header can be 0xF806 or 0xFC06
```

2023-05-23 01:30 UTC, cconcolato commented on index.bs
> +NOTE: Non-redundant Magic Code OBU (i.e. [=obu_redundant_copy=] = 0) coming after the first Magic Code OBU is regarded as the start of a new IA sequence. This could happen when concatenating 2 IA Seq
I think we should be explicit in the specification:
- The model part of the only defines a single IA Sequence. The IA Sequence starts with the first Magic Code OBU (typically non-redundant) and ends with the next non-redundant Magic Code OBU. There are consequences, e.g. Descriptor OBUs shall follow etc.
- The formats (standalone and/or ISOBMFF) may store one or more IA Sequences
- Readers shall support sequences.

2023-05-23 07:12 UTC, sunghee-hwang commented on index.bs
> +NOTE: Non-redundant Magic Code OBU (i.e. [=obu_redundant_copy=] = 0) coming after the first Magic Code OBU is regarded as the start of a new IA sequence. This could happen when concatenating 2 IA Seq
Why do we need the next non-redundant Magic Code OBU?
If we signals the end of IA sequence(s), don't you think that we need to use different type of OBU or out of band signal.

2023-05-23 18:39 UTC, cconcolato commented on index.bs
> +NOTE: Non-redundant Magic Code OBU (i.e. [=obu_redundant_copy=] = 0) coming after the first Magic Code OBU is regarded as the start of a new IA sequence. This could happen when concatenating 2 IA Seq
Redundant OBUs (whatever their type) should not matter except if they are the first one encountered by the reader. Otherwise, it means adding any redundant OBUs anywhere would change the semantics and processing of the stream.

2023-05-23 20:32 UTC, sunghee-hwang commented on index.bs
> +NOTE: Non-redundant Magic Code OBU (i.e. [=obu_redundant_copy=] = 0) coming after the first Magic Code OBU is regarded as the start of a new IA sequence. This could happen when concatenating 2 IA Seq
Oops~. I misunderstood that the next non redundant Magic Code OBU was a part of the current IA sequence to signal its end.

2023-05-23 20:38 UTC, sunghee-hwang commented on index.bs
> +NOTE: Non-redundant Magic Code OBU (i.e. [=obu_redundant_copy=] = 0) coming after the first Magic Code OBU is regarded as the start of a new IA sequence. This could happen when concatenating 2 IA Seq
If ISOBMFF stores multiple IA sequences, do you intend to support multiple sample entries?

2023-05-25 22:29 UTC, tdaede commented
We discussed this and ultimately we can define that IA sequences can be started with a new non redundant magic code OBU, and that it starts a new IA Sequence. We will not make specific decoding guarantees about multiple sequential sequences.

2023-05-25 22:30 UTC, tdaede approved these changes

2023-05-25 22:31 UTC, cconcolato approved these changes

2023-05-25 22:31 UTC, merged