Fix #399, Codec Config Improvement
AOMediaCodec/iamf pull request #426
Opened 2023-05-22 19:32 UTC by sunghee-hwang

2023-05-23 01:09 UTC, cconcolato requested changes

2023-05-23 01:09 UTC, cconcolato commented on index.bs
> +<dfn noexport>roll_distance</dfn> is a signed integer that gives the number of audio frames that need to be decoded in order for an audio frame to be decoded correctly. A positive value indicates the
Why do you need to define what a positive value means when both meaningful examples use negative values. I suggest changing the syntax to using signed integer.
The use of "that is a group member" is confusing. What is a group?

```suggestion
<dfn noexport>roll_distance</dfn>: for some audio codecs, even if an audio frame can be decoded independently, the decoded signal after decoding only that frame may not represent a perfect, decoded audio signal, even ignoring compression artifacts. This can be due to overlap transforms. While potentially acceptable when starting to decode a substream, it may be problematic when automatically switching between similar audio substreams of different quality and/or bitrate. The [=roll_distance=] field indicates how many audio frames prior to the current audio frame need to be decoded (and decoded samples discarded) to set the encoder in a state that will produce the perfect decoded audio signal. It shall be set to
```

2023-05-23 01:09 UTC, cconcolato commented on index.bs
> +- LPCM may ingore this field.
```suggestion
- It shall be set to the smallest integer greater than or equal to floor(3840 / [=num_samples_per_frame=]), when the [=codec_id=] is set to 'Opus'.
- It shall be set to 1 when the [=codec_id=] is set to 'mp4a'.
- It shall be set to 0 when the [=codec_id=] is set to 'fLaC' or 'ipcm'. 
```

2023-05-23 05:59 UTC, sunghee-hwang commented on index.bs
> +This flag shall be set to 0 for the current version of the specification (i.e. [=version=] = 0). An OBU parser which is conformant with the current version of the specification shall be able to parse
For example, V1.1 may have extension flag set. In that case, V1.0 parse could skip it because of knowing the size of extension field which is defined in V1.0.

2023-05-23 06:13 UTC, sunghee-hwang commented on index.bs
> +- LPCM may ingore this field.
I think the number needs to be minus value as the OBU itself is stored in sample entry.

2023-05-23 06:54 UTC, sunghee-hwang commented on index.bs
> +- 'ipcm' for LPCM: The payload of all substreams of all Audio Elements referring to this codec configuration shall be audio samples for linear PCM (LPCM) and the decoder_config() structure shall comp
Decode config of LPCM signals its bitdepth and endianess which is conform to MP4-PCM.

2023-06-05 22:39 UTC, tdaede commented
It looks like most of the comments in here have now been addressed, minus the negative roll_distance.

2023-06-05 23:04 UTC, tdaede commented on index.bs
> +- 'Opus' for OPUS: The payload of all substreams of all Audio Elements referring to this codec configuration shall comply to the specification [[!RFC6716]] and the decoder_config() structure shall co
"for OPUS" has been removed in this section.

2023-06-05 23:06 UTC, tdaede commented on index.bs
> +- 'ipcm' for LPCM: The payload of all substreams of all Audio Elements referring to this codec configuration shall be audio samples for linear PCM (LPCM) and the decoder_config() structure shall comp
This indirectly links to the normative reference via the lpcm-specific section. Would it be better to include that normative reference here too, or is the one-away link enough?

2023-06-05 23:07 UTC, tdaede approved these changes
Looks good once @cconcolato 's remaining issues are addressed (I see that most of them are addressed already).

2023-06-05 23:51 UTC, tdaede commented
needs rebase

2023-06-05 23:55 UTC, tdaede commented
I will try rebasing this locally

2023-06-06 00:09 UTC, cconcolato commented on index.bs
> +This flag shall be set to 0 for the current version of the specification (i.e. [=version=] = 0). An OBU parser which is conformant with the current version of the specification shall be able to parse
Then say:
> A parser conformant to this version of the specification shall skip any extension header bytes based on [=extension_header_size=] when the flag is set to 1.

2023-06-07 22:36 UTC, sunghee-hwang commented on index.bs
> +This flag shall be set to 0 for the current version of the specification (i.e. [=version=] = 0). An OBU parser which is conformant with the current version of the specification shall be able to parse
Addressed

2023-06-12 21:21 UTC, tdaede commented
I manually fixed this one up.

2023-06-12 21:31 UTC, merged