Fix #404, to support multiple labels in different languages
AOMediaCodec/iamf pull request #429
Opened 2023-05-23 01:38 UTC by sunghee-hwang

ISO 639-1 is more specific and direct reference than BCP47.

2023-05-23 01:45 UTC, cconcolato requested changes

2023-05-23 01:45 UTC, cconcolato commented on index.bs
> +    unsigned int (16) language_label;
why is the type `unsigned int (16)` and not simply `string`?

2023-05-23 01:45 UTC, cconcolato commented on index.bs
> +    mix_presentation_annotations();
why do you need a class and not simply use `string`

2023-05-23 02:02 UTC, cconcolato commented on index.bs
> +		"href": "https://www.iso.org/standard/22109.html"
ISO 639-1 is restricted compared to BCP-47. AFAIK, modern standards refer to BCP-47.

2023-05-23 06:24 UTC, sunghee-hwang commented on index.bs
> +    unsigned int (16) language_label;
Intention was to represent Alpha-2 code.

2023-05-23 06:25 UTC, sunghee-hwang commented on index.bs
> +    mix_presentation_annotations();
Annotation may be updated for a future version. It was proponent's proposal.

2023-05-24 07:16 UTC, sunghee-hwang commented on index.bs
> +    unsigned int (16) language_label;
I made further update to clarify 2CC language_label.

2023-05-26 17:18 UTC, sunghee-hwang commented
@cconcolato, please review it again.

2023-05-26 17:55 UTC, cconcolato requested changes

2023-05-26 17:55 UTC, cconcolato commented on index.bs
>   <b>string</b> indicates the type of a string which is terminated by null of one byte (i.e. 0x00).
```suggestion
<b>string</b> indicates a null-terminated (i.e. ending at the first byte set to 0x00), UTF-8 encoded as defined in [[!RFC3629]] and whose length shall be limited to 128 bytes. 
```

2023-05-26 17:55 UTC, cconcolato commented on index.bs
> + <b>syntaxName</b> is a human readable label whose byte representation consists of [=UTF-8_Enc(label)=]. Its length in bytes is limited to 128.
```suggestion
<b>syntaxName</b> is a human readable label.
```

2023-05-26 17:55 UTC, cconcolato commented on index.bs
I also suggest deleting the section 
```
### Function UTF-8 Encoding ### {#convention-function-utf8}
```

2023-05-26 19:01 UTC, sunghee-hwang commented on index.bs
@cconcolato , deleted the section. Please review it again. Thanks in advance.

2023-05-26 20:17 UTC, cconcolato approved these changes

2023-05-26 20:18 UTC, sunghee-hwang commented
As agreed, I do merge it.

2023-05-26 20:20 UTC, merged