Fix #492: Increase number of reserved OBU types by reducing
AOMediaCodec/iamf pull request #500
Opened 2023-06-21 21:01 UTC by felicialim

OBU_IA_Audio_Frame_ID21 to OBU_IA_Audio_Frame_ID17

This also renumbers obu_type for OBU_IA_Audio_Frame, OBU_IA_Audio_Frame{x}
  and Reserved.

2023-06-21 22:03 UTC, jwcullen approved these changes

2023-06-26 20:33 UTC, tdaede approved these changes

2023-06-26 22:59 UTC, tdaede commented
We will update this to one more reserved value and merge that.

2023-06-26 23:53 UTC, jwcullen requested changes
If we want to go with the idea to reduce the number reserved by 1.

2023-06-26 23:53 UTC, jwcullen commented on index.bs
> +  6~23  : OBU_IA_Audio_Frame_ID0 to OBU_IA_Audio_Frame_ID17
```suggestion
  6~22  : OBU_IA_Audio_Frame_ID0 to OBU_IA_Audio_Frame_ID16
```

2023-06-26 23:53 UTC, jwcullen commented on index.bs
> + 24~30  : Reserved
```suggestion
 23~30  : Reserved
```

2023-06-26 23:53 UTC, jwcullen commented on index.bs
> +- OBU_IA_Audio_Frame_ID0 to OBU_IA_Audio_Frame_ID17
```suggestion
- OBU_IA_Audio_Frame_ID0 to OBU_IA_Audio_Frame_ID16
```

2023-06-26 23:53 UTC, jwcullen commented on index.bs
> +<dfn noexport>obu_trimming_status_flag</dfn> indicates whether this OBU has audio samples to be trimmed or not. It SHALL be set only when [=obu_type=] is set to OBU_IA_Audio_Frame or OBU_IA_Audio_Fra
```suggestion
<dfn noexport>obu_trimming_status_flag</dfn> indicates whether this OBU has audio samples to be trimmed or not. It SHALL be set only when [=obu_type=] is set to OBU_IA_Audio_Frame or OBU_IA_Audio_Frame_ID0 to OBU_IA_Audio_Frame_ID16.
```

2023-06-26 23:53 UTC, jwcullen commented on index.bs
> +This section specifies OBU payloads of OBU_IA_Audio_Frame and OBU_IA_Audio_Frame_ID0 to OBU_IA_Audio_Frame_ID17.
```suggestion
This section specifies OBU payloads of OBU_IA_Audio_Frame and OBU_IA_Audio_Frame_ID0 to OBU_IA_Audio_Frame_ID16.
```

2023-06-26 23:53 UTC, jwcullen commented on index.bs
> +<dfn noexport>explicit_audio_substream_id</dfn> defines the [=audio_substream_id=] of this frame. The value SHALL be greater than 17. When this field is not present [=audio_substream_id=] is implicit
```suggestion
<dfn noexport>explicit_audio_substream_id</dfn> defines the [=audio_substream_id=] of this frame. The value SHALL be greater than 16. When this field is not present [=audio_substream_id=] is implicit and is defined as a value from 0 to 16 for OBU_IA_Audio_Frame_ID0 to OBU_IA_Audio_Frame_ID16 respectively.
```

2023-06-26 23:53 UTC, jwcullen commented on index.bs
> +NOTE: The first 18 [=Audio Substream=]s in an [=IA Sequence=] MAY use the OBU types OBU_IA_Audio_Frame_ID0 to OBU_IA_Audio_Frame_ID17, which have predefined [=audio_substream_id=]s associated with th
```suggestion
NOTE: The first 17 [=Audio Substream=]s in an [=IA Sequence=] MAY use the OBU types OBU_IA_Audio_Frame_ID0 to OBU_IA_Audio_Frame_ID16, which have predefined [=audio_substream_id=]s associated with them. This reduces bitrate by avoiding the extra [=explicit_audio_substream_id=] field in the bitstream.
```

2023-06-27 22:33 UTC, merged