Fix #499, profile_name -> primary_profile
AOMediaCodec/iamf pull request #505
Opened 2023-06-23 00:36 UTC by sunghee-hwang

2023-06-26 20:42 UTC, cconcolato requested changes

2023-06-26 20:42 UTC, cconcolato commented on index.bs
> +<dfn noexport>primary_profile</dfn> indicates that this [=IA Sequence=] is able to be processed by IA decoders that support the profile indicated in this field. The IA decoders SHALL be able to parse
```suggestion
<dfn noexport>primary_profile</dfn> indicates the primary profile this [=IA Sequence=] complies to. Parsers compliant to this version of the specification SHALL discard the [=IA Sequence=] when this value is not one they support.
```
The rest of the text should go to the section about profiles:
``IA decoders SHALL be able to parse all OBUs explicitly listed in a profile they support. They can still encounter reserved OBUs that they SHOULD skip. This allows future versions of the specification to define new profiles that can be backwards compatible to old profiles.
```

2023-06-26 20:42 UTC, cconcolato commented on index.bs
> +<dfn noexport>additional_profile</dfn> indicates an additional profile of this specification to which this [=IA Sequence=] complies. If an [=IA Sequence=] only complies with the [=primary_profile=] p
Why add the restriction that it shall be greater? It depends on how profiles are defined. I suggest using SHOULD and remove the last sentence.

2023-06-26 20:42 UTC, cconcolato commented on index.bs
> +NOTE: For example, an [=IA Sequence=] with [=primary_profile=] = 0 and [=additional_profile=] = 1 means that the [=IA Sequence=] complies to Base profile of specification and IA decoder to support Si
The example of Simple/Base is not the best choice because both profiles are defined in the same version of the spec. It is clear that a Simple bitstream can be decoded by a Base decoder.
The second example should not use a real name like 'Enhanced'. 
```suggestion
NOTE: If a future version defines a new profile, e.g. HypotheticalProfile, that is backwards compatible with the Base profile, for example by defining new OBUs that would be ignored by the Base-compatible parser, a IA writer can decide to set the [=primary_profile=] to 'Base' while setting the [=additional_profile=] to 'HypotheticalProfile'. This way an old processor will know it can parse and produce an acceptable rendering, while a new processor still know it can produce a better result because it will not ignore the additional features.
```

2023-06-26 20:42 UTC, cconcolato commented on index.bs
> +- [=additional_profile=] SHALL be set to 0 to indicate that the [=IA Sequence=] complies to this profile.
The profile definition should not have any restrictions on `additional_profile` because otherwise future streams cannot be backwards compatible with this profile.

2023-06-26 20:42 UTC, cconcolato commented on index.bs
> +- [=additional_profile=] SHALL be set to 1 to indicate that the [=IA Sequence=] complies to this profile.
Same comment as above.

2023-06-26 22:16 UTC, tdaede commented on index.bs
> +<dfn noexport>additional_profile</dfn> indicates an additional profile of this specification to which this [=IA Sequence=] complies. If an [=IA Sequence=] only complies with the [=primary_profile=] p
The concern is that if profile compatibility becomes an arbitrary tree, we might need more than 2 profile fields. But we can be careful to not create that sort of situation.

We can remove the restriction on "greater than" to solve this (as Cyril commented).

2023-06-26 22:20 UTC, tdaede commented on index.bs
> +- [=additional_profile=] SHALL be set to 0 to indicate that the [=IA Sequence=] complies to this profile.
We'll remove this restriction.

2023-06-26 23:44 UTC, sunghee-hwang commented on index.bs
> +NOTE: For example, an [=IA Sequence=] with [=primary_profile=] = 0 and [=additional_profile=] = 1 means that the [=IA Sequence=] complies to Base profile of specification and IA decoder to support Si
> The example of Simple/Base is not the best choice because both profiles are defined in the same version of the spec. It is clear that a Simple bitstream can be decoded by a Base decoder. The second example should not use a real name like 'Enhanced'.

```suggestion
NOTE: If a future version defines a new profile, e.g. HypotheticalProfile, that is backwards compatible with the Base profile, for example by defining new OBUs that would be ignored by the Base-compatible parser, a IA writer can decide to set the [=primary_profile=] to 'Base' while setting the [=additional_profile=] to 'HypotheticalProfile'. This way an old processor will know it can parse and produce an acceptable rendering, while a new processor still knows it can produce a better result because it will not ignore the additional featurest.
```

2023-06-28 00:12 UTC, sunghee-hwang commented on index.bs
> +<dfn noexport>additional_profile</dfn> indicates an additional profile of this specification to which this [=IA Sequence=] complies. If an [=IA Sequence=] only complies with the [=primary_profile=] p
```suggestion
<dfn noexport>additional_profile</dfn> indicates an additional profile of this specification to which this [=IA Sequence=] complies. If an [=IA Sequence=] only complies with the [=primary_profile=] profile, this field SHALL be set to same [=primary_profile=] value. Parsers compliant to this version of the specification SHALL discard this OBU with the value of [=additional_profile=] < the value of [=primary_value=] and all subsequent OBUs until encounting the next [=IA Sequence Header OBU=].
```

2023-06-28 00:18 UTC, sunghee-hwang commented on index.bs
> +<dfn noexport>additional_profile</dfn> indicates an additional profile of this specification to which this [=IA Sequence=] complies. If an [=IA Sequence=] only complies with the [=primary_profile=] p
```suggestion
<dfn noexport>additional_profile</dfn> indicates an additional profile of this specification to which this [=IA Sequence=] complies. If an [=IA Sequence=] only complies with the [=primary_profile=] profile, this field SHALL be set to same [=primary_profile=] value.
```

2023-06-28 00:18 UTC, cconcolato approved these changes

2023-06-28 00:19 UTC, merged