Fix #511, explicitly limit decoded leb128() to 32 bits
AOMediaCodec/iamf pull request #558
Opened 2023-06-29 23:06 UTC by sunghee-hwang

2023-06-30 20:34 UTC, jwcullen requested changes
Two comments

- Perhaps remove `sleb128`. It is not used elsewhere in the spec and it was dropped when Sync OBU was dropped.
- We used to define `leb128` from [AV1](https://aomediacodec.github.io/av1-spec/#leb128). AV1 has a note which allows multiple ways to encode the same value. For example 0 can be encoded as 0x00 or 0x8000., or 0x800000...

_Note: There are multiple ways of encoding the same value depending on how many leading zero bits are encoded. There is no requirement that this syntax descriptor uses the most compressed representation. This can be useful for encoder implementations by allowing a fixed amount of space to be filled in later when the value becomes known._

I think the new definition drops the ability to a `leb128` to be encoded multiple ways as in AV1. It would force 0 to always be encoded as 0x00 for example.

I think the flexibility of allowing multiple representations could have some value in the future. Perhaps some implementations would prefer to allocate fixed sizes for their leb128 values instead of using the minimal representation.

Since we were pulling in the definition from AV1 before this shouldn't be a bitstream change.

2023-07-04 21:18 UTC, sunghee-hwang commented on index.bs
> + <b>leb128()</b> indicates the type of an unsigned integer. To encode the following unsigned integer <b>syntaxName</b>, it first represents the integer in binary. Then zero extends the integer up to
```suggestion
 <b>leb128()</b> indicates the type of an unsigned integer. To encode the following unsigned integer <b>syntaxName</b>, it first represents the integer in binary with an N-bit representation, where N ia a multiple of 7. Then break the integer up into groups of 7 bits. Output one encoded byte for each 7 bits group, from least significant to most significant group. Each byte will have the group in its 7 least significant bits. Set the most significant bit on each byte except the last byte.
```

2023-07-04 21:25 UTC, sunghee-hwang commented on index.bs
> + <b>leb128()</b> indicates the type of an unsigned integer. To encode the following unsigned integer <b>syntaxName</b>, it first represents the integer in binary with an N-bit representation, where N
```suggestion
 <b>leb128()</b> indicates the type of an unsigned integer. To encode the following unsigned integer <b>syntaxName</b>, it first represents the integer in binary with an N-bit representation, where N is a multiple of 7. Then break the integer up into groups of 7 bits. Output one encoded byte for each 7 bits group, from least significant to most significant group. Each byte will have the group in its 7 least significant bits. Set the most significant bit on each byte except the last byte.
```

2023-07-05 23:49 UTC, jwcullen approved these changes

2023-07-05 23:49 UTC, tdaede commented
We will re-add the note in a follow up PR.

2023-07-05 23:49 UTC, merged

2023-07-05 23:49 UTC, jwcullen commented
Approved as limiting to 32 bits and rewording to remove direct reference to AV1.