Sections 6.3, 6.4: improve text
AOMediaCodec/iamf pull request #599
Opened 2023-07-06 22:51 UTC by felicialim

2023-07-07 07:38 UTC, sunghee-hwang requested changes

2023-07-07 07:38 UTC, sunghee-hwang commented on index.bs
> +2. Next, place the OBUs from the <code>j = 1, 2, ..., m</code>-th [=IASampleEntry=]s in the [=IA Sequence=], in order. These form the <code>j = 1, 2, ..., m</code>-th [=Temporal Unit=]s.
```suggestion
2. Next, place the OBUs from the <code>j = 1, 2, ..., m</code>-th [=IA Sample=]s associated with the [=IASampleEntry=] in the [=IA Sequence=], in order. These form the <code>j = 1, 2, ..., m</code>-th [=Temporal Unit=]s.
```

2023-07-10 23:12 UTC, tdaede commented
Suggested change is committed. Overriding change request.

2023-07-10 23:12 UTC, tdaede approved these changes

2023-07-10 23:13 UTC, merged