Simplify division symbols
AOMediaCodec/iamf pull request #630
Opened 2023-07-12 18:42 UTC by felicialim

Drop "integer division with truncation of the result toward zero" since we can represent that with floor(x / y).

2023-07-12 18:44 UTC, felicialim commented
There are a few more uses of `/` in the sections below, but with this change, I think they're correct now (i.e. should be floating point division, not int divisions). @sunghee-hwang Could you please check as well?

7.2.1 Gain
7.2.2 De-Mixer
7.2.3 Recon Gain
10.2.4. Annex B-4: Recon Gain Generation

2023-07-12 23:08 UTC, sunghee-hwang commented
@felicialim, how about making PR #627, #628, #630, and #631 as one single PR or fully separated ones?

From past experience, we had lost something during the merging of multiple PRs complicating each other so we should create another PR to fix it.

2023-07-12 23:09 UTC, sunghee-hwang commented
> There are a few more uses of `/` in the sections below, but with this change, I think they're correct now (i.e. should be floating point division, not int divisions). @sunghee-hwang Could you please check as well?
> 
> 7.2.1 Gain 7.2.2 De-Mixer 7.2.3 Recon Gain 10.2.4. Annex B-4: Recon Gain Generation

Sure, I will.

2023-07-12 23:18 UTC, sunghee-hwang commented
> > There are a few more uses of `/` in the sections below, but with this change, I think they're correct now (i.e. should be floating point division, not int divisions). @sunghee-hwang Could you please check as well?
> > 7.2.1 Gain 7.2.2 De-Mixer 7.2.3 Recon Gain 10.2.4. Annex B-4: Recon Gain Generation
> 
> Sure, I will.

I have checked the sections, and they are fine. But, generally, I realize that there are many places to use '/' in other usages.
So, it would be better to use '÷' rather than '/'.

2023-07-12 23:39 UTC, felicialim commented
> @felicialim, how about making PR #627, #628, #630, and #631 as one single PR or fully separated ones?
> 
> From past experience, we had lost something during the merging of multiple PRs complicating each other so we should create another PR to fix it.

Alternatively, how about if we merge these smaller approved PRs offline before the weekly meeting? @tdaede

2023-07-12 23:45 UTC, felicialim commented
> > > There are a few more uses of `/` in the sections below, but with this change, I think they're correct now (i.e. should be floating point division, not int divisions). @sunghee-hwang Could you please check as well?
> > > 7.2.1 Gain 7.2.2 De-Mixer 7.2.3 Recon Gain 10.2.4. Annex B-4: Recon Gain Generation
> > 
> > 
> > Sure, I will.
> 
> I have checked the sections, and they are fine. But, generally, I realize that there are many places to use '/' in other usages. So, it would be better to use '÷' rather than '/'.

Do you mean we should still keep one division symbol only, but use "÷" instead of "/"? 

My preference is for "/" because it seems more natural to use "/" (from the high number of occurrence here, and from the mistakes we'd also caught in previous PRs) so this may help prevent accidental mistakes when making future extensions to the spec.

2023-07-12 23:46 UTC, sunghee-hwang commented
> > @felicialim, how about making PR #627, #628, #630, and #631 as one single PR or fully separated ones?
> > From past experience, we had lost something during the merging of multiple PRs complicating each other so we should create another PR to fix it.
> 
> Alternatively, how about if we merge these smaller PRs offline (after approval) before the weekly meeting? @tdaede

@felicialim @tdaede , I am fine if it would work.

2023-07-12 23:50 UTC, sunghee-hwang commented
> > > > There are a few more uses of `/` in the sections below, but with this change, I think they're correct now (i.e. should be floating point division, not int divisions). @sunghee-hwang Could you please check as well?
> > > > 7.2.1 Gain 7.2.2 De-Mixer 7.2.3 Recon Gain 10.2.4. Annex B-4: Recon Gain Generation
> > > 
> > > 
> > > Sure, I will.
> > 
> > 
> > I have checked the sections, and they are fine. But, generally, I realize that there are many places to use '/' in other usages. So, it would be better to use '÷' rather than '/'.
> 
> Do you mean we should still keep one division symbol only, but use "÷" instead of "/"?
> 
> My preference is for "/" because it seems more natural to use "/" (from the high number of occurrence here, and from the mistakes we'd also caught in previous PRs) so this may help prevent accidental mistakes when making future extensions to the spec.

Yes, if you search the spec by using the keyword '/', there are so many places to use it in different usage.

2023-07-13 00:07 UTC, sunghee-hwang commented
> > > > > There are a few more uses of `/` in the sections below, but with this change, I think they're correct now (i.e. should be floating point division, not int divisions). @sunghee-hwang Could you please check as well?
> > > > > 7.2.1 Gain 7.2.2 De-Mixer 7.2.3 Recon Gain 10.2.4. Annex B-4: Recon Gain Generation
> > > > 
> > > > 
> > > > Sure, I will.
> > > 
> > > 
> > > I have checked the sections, and they are fine. But, generally, I realize that there are many places to use '/' in other usages. So, it would be better to use '÷' rather than '/'.
> > 
> > 
> > Do you mean we should still keep one division symbol only, but use "÷" instead of "/"?
> > My preference is for "/" because it seems more natural to use "/" (from the high number of occurrence here, and from the mistakes we'd also caught in previous PRs) so this may help prevent accidental mistakes when making future extensions to the spec.
> 
> Yes, if you search the spec by using the keyword '/', there are so many places to use it in different usage.

@felicialim, did you contact him? How about texting or calling to him?

2023-07-13 00:18 UTC, sunghee-hwang commented
> > > > > There are a few more uses of `/` in the sections below, but with this change, I think they're correct now (i.e. should be floating point division, not int divisions). @sunghee-hwang Could you please check as well?
> > > > > 7.2.1 Gain 7.2.2 De-Mixer 7.2.3 Recon Gain 10.2.4. Annex B-4: Recon Gain Generation
> > > > 
> > > > 
> > > > Sure, I will.
> > > 
> > > 
> > > I have checked the sections, and they are fine. But, generally, I realize that there are many places to use '/' in other usages. So, it would be better to use '÷' rather than '/'.
> > 
> > 
> > Do you mean we should still keep one division symbol only, but use "÷" instead of "/"?
> > My preference is for "/" because it seems more natural to use "/" (from the high number of occurrence here, and from the mistakes we'd also caught in previous PRs) so this may help prevent accidental mistakes when making future extensions to the spec.
> 
> Yes, if you search the spec by using the keyword '/', there are so many places to use it in different usage.


@felicialim 
Let's go ahead with '/' as the industry has used it for multiple purposes. I will update the places which are using '/' in different usages if needed. Please reply to this when you read this.

2023-07-13 01:49 UTC, felicialim commented
> > > > > > There are a few more uses of `/` in the sections below, but with this change, I think they're correct now (i.e. should be floating point division, not int divisions). @sunghee-hwang Could you please check as well?
> > > > > > 7.2.1 Gain 7.2.2 De-Mixer 7.2.3 Recon Gain 10.2.4. Annex B-4: Recon Gain Generation
> > > > > 
> > > > > 
> > > > > Sure, I will.
> > > > 
> > > > 
> > > > I have checked the sections, and they are fine. But, generally, I realize that there are many places to use '/' in other usages. So, it would be better to use '÷' rather than '/'.
> > > 
> > > 
> > > Do you mean we should still keep one division symbol only, but use "÷" instead of "/"?
> > > My preference is for "/" because it seems more natural to use "/" (from the high number of occurrence here, and from the mistakes we'd also caught in previous PRs) so this may help prevent accidental mistakes when making future extensions to the spec.
> > 
> > 
> > Yes, if you search the spec by using the keyword '/', there are so many places to use it in different usage.
> 
> @felicialim Let's go ahead with '/' as the industry has used it for multiple purposes. I will update the places which are using '/' in different usages if needed. Please reply to this when you read this.

Sounds good. Most other "/" are hopefully obvious they aren't divisions, but I agree there could be a few places where it's ambiguous. Thanks for updating any that you see.

2023-07-13 02:31 UTC, sunghee-hwang reviewed
÷ to /

2023-07-13 02:31 UTC, sunghee-hwang commented on index.bs
> +- It SHALL be set to -R when [=codec_id=] is set to 'Opus'. Where R is ceil(3840 ÷ [=num_samples_per_frame=]).
```suggestion
- It SHALL be set to -R when [=codec_id=] is set to 'Opus'. Where R is ceil(3840 / [=num_samples_per_frame=]).
```

2023-07-13 02:35 UTC, sunghee-hwang requested changes
Should it be like this?

2023-07-13 02:35 UTC, sunghee-hwang commented on index.bs
> +n2 = t2 * floor(audio_sample_rate / parameter_rate).
```suggestion
n0 = floor(t0 * (audio_sample_rate / parameter_rate)),
n1 = floor(t1 * (audio_sample_rate / parameter_rate)),
n2 = floor(t2 * (audio_sample_rate / parameter_rate).
```

2023-07-13 05:18 UTC, sunghee-hwang approved these changes

2023-07-13 05:19 UTC, sunghee-hwang commented on index.bs
> +n2 = floor(t2 * (audio_sample_rate / parameter_rate).
```suggestion
n2 = floor(t2 * (audio_sample_rate / parameter_rate)).
```

2023-07-14 04:46 UTC, sunghee-hwang commented on index.bs
> +- It SHALL be set to -R when [=codec_id=] is set to 'Opus'. Where R is ceil(3840 / [=num_samples_per_frame=]).
```suggestion
- It SHALL be set to -R when [=codec_id=] is set to 'Opus', where R is <code>ceil(3840 / [=num_samples_per_frame=])</code>.
```

2023-07-14 04:48 UTC, sunghee-hwang commented on index.bs
>  <dfn noexport>audio_roll_distance</dfn> indicates how many audio frames prior to the current audio frame need to be decoded (and decoded samples discarded) to set the encoder in a state that will pro
```suggestion
<dfn noexport>audio_roll_distance</dfn> indicates how many audio frames prior to the current audio frame need to be decoded (and the decoded samples discarded) to set the encoder in a state that will produce the perfect decoded audio signal. It SHALL always be a negative value or zero. For some audio codecs, even if an audio frame can be decoded independently, the decoded signal after decoding only that frame may not represent a perfect, decoded audio signal, even ignoring compression artifacts. This can be due to overlap transforms. While potentially acceptable when starting to decode an [=Audio Substream=], it may be problematic when automatically switching between similar [=Audio Substream=]s of different quality and/or bitrate. 
```

2023-07-17 18:01 UTC, felicialim commented on index.bs
> +- Where, Ltf2 and Rtf2 are top channels of x.1.2ch, Ltf3 and Rtf3 are top channels of 3.1.2ch, and Ltf4 and Rtf4 are top channels of x.1.4ch (x = 5 or 7) and [=w(k)=] is determined from the value of
```suggestion
- Where, Ltf2 and Rtf2 are the top channels of x.1.2ch, Ltf3 and Rtf3 are the top channels of 3.1.2ch, and Ltf4 and Rtf4 are the top channels of x.1.4ch (x = 5 or 7) and [=w(k)=] is determined from the value of wIdx(k).
```

2023-07-17 22:41 UTC, merged