Changes to properly indicate scope and informative parts according to…
AOMediaCodec/iamf pull request #726
Opened 2023-08-23 22:38 UTC by podborski

… Apple's proposal document. (Section reordering not included)

2023-08-23 23:37 UTC, sunghee-hwang commented on index.bs
> +- A Renderer can be used to render the [=Element=]s to a multi-channel or binaural format based on [=Descriptors=].
```suggestion
- An Element Rebuilder re-assembles the [=Audio Element=]s by combining the [=Channel Group=](s) guided by [=Descriptors=] and [=Parameter Substream=](s).
- A Renderer can be used to render the [=Audio Element=]s to a multi-channel or binaural format based on [=Descriptors=].
```

2023-08-23 23:38 UTC, sunghee-hwang reviewed
They should be "Audio Element"

2023-08-23 23:43 UTC, sunghee-hwang commented on index.bs
> +As stated in [[Architecture]], specific renderers are out of scope. Examples provided are informative.
```suggestion
As stated in [[#Architecture]], specific renderers are out of scope. Examples provided are informative.
```

2023-08-23 23:43 UTC, sunghee-hwang reviewed
They should be "Audio Element"

2023-08-23 23:55 UTC, sunghee-hwang commented
@Frank-Ba, 
I think that the color for both "Renderer" and "Post-Processor" of the updated figure (IAMF architecture) need to be changed to the one for In Scope (Informative) like as Pre-Processor and OBU Packetizer.

2023-08-23 23:59 UTC, sunghee-hwang requested changes

2023-08-23 23:59 UTC, sunghee-hwang commented on index.bs
> +- A Renderer can be used to render the [=Element=]s to a multi-channel or binaural format based on [=Descriptors=].
```suggestion
- An Element Rebuilder re-assembles the [=Audio Element=]s by combining the [=Channel Group=](s) guided by [=Descriptors=] and [=Parameter Substream=](s).
- A Renderer can be used to render the [=Audio Element=]s to a multi-channel or binaural format based on [=Descriptors=].
```

2023-08-23 23:59 UTC, sunghee-hwang commented on index.bs
> +As stated in [[Architecture]], specific renderers are out of scope. Examples provided are informative.
```suggestion
As stated in [[#Architecture]], specific renderers are out of scope. Examples provided are informative.
```

2023-08-24 00:12 UTC, sunghee-hwang submitted a review, later dismissed

2023-08-24 00:14 UTC, Frank-Ba commented
@ sunghee-hwang The charter says: "The definition of audio signals is out of scope ..." That's why the renderer and post-processor blocks are out of scope.

2023-08-24 00:21 UTC, sunghee-hwang reviewed
To fix fatal error

2023-08-24 00:21 UTC, sunghee-hwang commented on index.bs
> +As stated in [[#Architecture]], specific renderers are out of scope. Examples provided are informative.
```suggestion
As stated in [[#architecture]], specific renderers are out of scope. The examples provided are informative.
```

2023-08-24 00:34 UTC, Frank-Ba commented
I am not able to parse the HTML file. It stops with this error:
stderr: 'remote: Permission to Frank-Ba/iamf.git denied to github-actions[bot].\n' +
[1029](https://github.com/Frank-Ba/iamf/actions/runs/5957922371/job/16161401292#step:3:1050)
      "fatal: unable to access 'https://github.com/Frank-Ba/iamf.git/': The requested URL returned error: 403",
[1030](https://github.com/Frank-Ba/iamf/actions/runs/5957922371/job/16161401292#step:3:1051)
    code: 128
[1031](https://github.com/Frank-Ba/iamf/actions/runs/5957922371/job/16161401292#step:3:1052)

2023-08-24 00:51 UTC, sunghee-hwang commented
> I am not able to parse the HTML file. It stops with this error: stderr: 'remote: Permission to Frank-Ba/iamf.git denied to github-actions[bot].\n' + [1029](https://github.com/Frank-Ba/iamf/actions/runs/5957922371/job/16161401292#step:3:1050) "fatal: unable to access 'https://github.com/Frank-Ba/iamf.git/': The requested URL returned error: 403", [1030](https://github.com/Frank-Ba/iamf/actions/runs/5957922371/job/16161401292#step:3:1051) code: 128 [1031](https://github.com/Frank-Ba/iamf/actions/runs/5957922371/job/16161401292#step:3:1052)

Now, it works.

2023-08-24 17:37 UTC, Frank-Ba commented
> I think that the meaning of "In Scope" in the figure differs from that in WG charter.

@sunghee-hwang One goal of the proposed changes is to bring the document in line with the charter. I am not aware of a different definition of Scope or how it could be interpreted in a different way than what is given in the charter.

2023-08-24 20:55 UTC, felicialim commented on index.bs
> +- An Element Rebuilder re-assembles the [=Audio Element=]s by combining the [=Channel Group=](s) guided by [=Descriptors=] and [=Parameter Substream=](s).
How about "Element Reconstructor" instead of "Element Rebuilder", as we've already used the term "reconstruct" elsewhere in the spec.

2023-08-24 20:55 UTC, felicialim commented on index.bs
> +If the EAR HOA renderer is used, the following metadata can be provided to the renderer for each audio channel:
"can be" -> "is" to be consistent with "Configuring the EAR Direct Speakers Renderer"

2023-08-25 01:45 UTC, sunghee-hwang commented
> > I think that the meaning of "In Scope" in the figure differs from that in WG charter.
> 
> @sunghee-hwang One goal of the proposed changes is to bring the document in line with the charter. I am not aware of a different definition of Scope or how it could be interpreted in a different way than what is given in the charter.

I am not trying to interpret the charter in a different way.
Regardless of the charter, what I am trying to say is that the spec is handling the renderer and the post-processor in scope but informative.

2023-08-25 16:50 UTC, Frank-Ba commented
> I am not trying to interpret the charter in a different way.
> Regardless of the charter, what I am trying to say is that the spec is handling the renderer and the post-processor in scope but informative.

@sunghee-hwang Since the term scope is not used in the document except for Fig. 2, I propose to remove it from Figure 2  to avoid any confusion. (Please see my updated figure)

2023-08-25 17:07 UTC, sunghee-hwang commented
> > I am not trying to interpret the charter in a different way.
> > Regardless of the charter, what I am trying to say is that the spec is handling the renderer and the post-processor in scope but informative.
> 
> @sunghee-hwang Since the term scope is not used in the document except for Fig. 2, I propose to remove it from Figure 2 to avoid any confusion. (Please see my updated figure)

Looks good!

2023-08-25 17:16 UTC, sunghee-hwang commented
I am not sure where the conflicts come from.
Usually, it has shown a link for "resolve conflicts". 
But the is not shown to me.
Can you see the link for "resolve conflicts"?
Otherwise, I guess that it has happened after the commit 22f7929.

2023-08-25 17:35 UTC, Frank-Ba commented
@sunghee-hwang I can see the button to resolve conflicts, but the conflicts show up in yellow without providing any way to resolve them. I also don't see the conflicts in my local clone of the repo. Not sure how to proceed ...
<img width="233" alt="Screenshot 2023-08-25 at 10 33 35 AM" src="https://github.com/AOMediaCodec/iamf/assets/46942654/4630d12b-ddd0-49b2-8c52-4d55401f83d6">

2023-08-25 19:16 UTC, felicialim commented
> @sunghee-hwang I can see the button to resolve conflicts, but the conflicts show up in yellow without providing any way to resolve them. I also don't see the conflicts in my local clone of the repo. Not sure how to proceed ... <img alt="Screenshot 2023-08-25 at 10 33 35 AM" width="233" src="https://user-images.githubusercontent.com/46942654/263349542-4630d12b-ddd0-49b2-8c52-4d55401f83d6.png">

I believe you can directly edit the text in that window and then commit the changes.

2023-08-27 23:42 UTC, sunghee-hwang commented
@Frank-Ba 
If you don't mind, can you kindly change the color for normative modules to the old one (light green)?
The colors on the several updated figures in PR #727 were based on the old ones.

2023-08-28 07:55 UTC, sunghee-hwang commented on index.bs
> +- A Post-Processor outputs an [=Immersive Audio=] by using the [=Channel Group=](s), [=Descriptors=] and [=Parameter Substream=](s).
```suggestion
- A Mixer sums the rendered [=Audio Element=]s and applies further mixing parameters guided by the [=Descriptors=] and the [=Parameter Substream=](s).
- A Post-Processor outputs an [=Immersive Audio=] by using the [=Channel Group=](s), the [=Descriptors=], and the [=Parameter Substream=](s).
```

2023-08-28 07:55 UTC, sunghee-hwang commented on index.bs
>  The Pre-Processor, [=Channel Group=](s), Codec Encoder, and OBU Packetizer are defined in [[#iamfgeneration]]. The [=IA Sequence=] is defined in [[#standalone-ia-sequence]]. The OBU Parser, Codec Dec
```suggestion
An IAMF generation processing including the Pre-Processor, the [=Channel Group=](s), the Codec Encoder, and the OBU Packetizer are defined in [[#iamfgeneration]]. The [=IA Sequence=] is defined in [[#standalone-ia-sequence]]. An IAMF processing including the OBU Parser, the Codec Decoder, the Element Reconstructor, the Renderer, the Mixer, and the Post-Processor are defined in [[#processing]].
```

2023-08-28 16:07 UTC, Frank-Ba commented
> If you don't mind, can you kindly change the color for normative modules to the old one (light green)?
> The colors on the several updated figures in PR https://github.com/AOMediaCodec/iamf/pull/727 were based on the old ones.
I changed the colors. Please note that the legend of Fig. 2 is only applicable to Fig. 2

2023-08-28 21:51 UTC, sunghee-hwang approved these changes

2023-08-28 22:50 UTC, felicialim commented on index.bs
> +- They SHALL be able to handle up to 16 channels.
The same change should be done for the Base Profile (current wording: "They SHALL be able to decode and process up to 18 channels.")

2023-08-28 23:10 UTC, tdaede commented
We will merge this once Felicia's most recent suggestion is included and the branch is rebased.

2023-08-28 23:16 UTC, Frank-Ba commented on index.bs
> +- They SHALL be able to handle up to 16 channels.
I added the change to the PR.

2023-08-28 23:25 UTC, felicialim approved these changes

2023-08-28 23:25 UTC, merged