Specify CENC
AOMediaCodec/iamf pull request #827
Opened 2024-05-28 22:14 UTC by felicialim

Fix 820

2024-05-29 00:56 UTC, sunghee-hwang approved these changes

2024-06-12 09:14 UTC, yilun-zhangs commented
@felicialim 
Dose it need to specify which encryption types will be supported? `full sample encryption`, `subsample encryption`, 
`pattern encryption`, one or more.

2024-06-14 00:41 UTC, sunghee-hwang requested changes
- The version of CENC reference is aligned with that of av1-isobmff.
- The restriction for encryption modes is removed. (to reflect WG's comment)

2024-06-14 00:41 UTC, sunghee-hwang commented on index.bs
> +		"href" : "https://www.iso.org/standard/84637.html"
```suggestion
		"href" : "https://www.iso.org/standard/68042.html"
```

2024-06-14 00:41 UTC, sunghee-hwang commented on index.bs
> +[=IA Track=]s MAY be protected. If protected, they SHALL conform to [[!CENC]]. Files SHOULD be protected using the [=cbcs=] protection scheme and MAY be protected using the [=cenc=] protection scheme
```suggestion
[=IA Track=]s MAY be protected. If protected, they SHALL conform to [[!CENC]].
```

2024-06-14 00:41 UTC, sunghee-hwang commented on index.bs
> +
```suggestion
```

2024-06-14 20:28 UTC, felicialim commented
> @felicialim Dose it need to specify which encryption types will be supported? `full sample encryption`, `subsample encryption`, `pattern encryption`, one or more.

According to the ISOBMFF spec, (whole-block) full sample should be used for audio. I've added some text to clarify it, please take a look.

2024-06-17 05:47 UTC, sunghee-hwang approved these changes
LGTM

2024-06-17 18:38 UTC, cconcolato commented on index.bs
> +- It SHALL contain at least one track using an [=IASampleEntry=], possibly transformed by encryption as specified in [[#commonencryption]].
Strictly speaking an "old" implementation of v1.0 could have assumed that files would never have encrypted IAMF tracks. I wonder if this warrants a new brand to signal the possible encryption.

2024-06-17 18:39 UTC, cconcolato commented on index.bs
> +When the protection schemes [=cenc=] or [=cbc1=] are used, an [=IA Track=] SHALL be protected using full sample encryption. When the protection schemes [=cens=] or [=cbcs=] are used, an [=IA Track=]
This is a lot of options, and therefore a lot of testing, and possible market fragmentation. Can't the group agree on one approach only?

2024-06-17 23:08 UTC, tdaede commented on index.bs
> +- It SHALL contain at least one track using an [=IASampleEntry=], possibly transformed by encryption as specified in [[#commonencryption]].
We already have box presence to signal CENC presence. We decided to not require new profiles to use CENC. If there are other examples of codecs that use brands to signal encryption presence we can do the same.

2024-06-17 23:18 UTC, tdaede commented on index.bs
> +When the protection schemes [=cenc=] or [=cbc1=] are used, an [=IA Track=] SHALL be protected using full sample encryption. When the protection schemes [=cens=] or [=cbcs=] are used, an [=IA Track=]
The problem is CENC is mandatory in ISOBMFF, but CBCS is more widely used. We could pretty easily reduce it to two. Reducing it to one might be more difficult.

2024-06-17 23:26 UTC, merged